import copy
import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

pytestmark = [pytest.mark.contract, pytest.mark.unit]


SNAPSHOT_PATH = Path(__file__).parent / "openapi_snapshot.json"

# These schemas are auto-generated by Pydantic/FastAPI and vary by Python
# version (e.g. Python 3.11 adds "ctx" and "input" sub-schemas to
# ValidationError). They are NOT part of our application contract.
_PYDANTIC_INTERNAL_SCHEMAS = {
    "HTTPValidationError",
    "ValidationError",
}


def _normalized_json(obj) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False)


def _strip_pydantic_schemas(schema: dict) -> dict:
    """Remove Pydantic-internal schemas that differ across Python versions."""
    schema = copy.deepcopy(schema)
    components = schema.get("components", {})
    schemas = components.get("schemas", {})
    for name in _PYDANTIC_INTERNAL_SCHEMAS:
        schemas.pop(name, None)
    if schemas:
        components["schemas"] = schemas
    return schema


def test_openapi_snapshot_is_stable(request: pytest.FixtureRequest):
    # Import after pytest autouse env fixture disables scheduler/create-tables.
    from app.core.config import settings
    from app.main import app

    original = settings.DOCS_ENABLED
    settings.DOCS_ENABLED = True
    try:
        client = TestClient(app)
        resp = client.get("/api/v1/openapi.json")
    finally:
        settings.DOCS_ENABLED = original

    assert resp.status_code == 200

    current = _strip_pydantic_schemas(resp.json())

    if request.config.getoption("--update-openapi-snapshot"):
        SNAPSHOT_PATH.write_text(_normalized_json(current) + "\n", encoding="utf-8")
        return

    if not SNAPSHOT_PATH.exists():
        pytest.fail(
            "OpenAPI snapshot missing. Generate it by running: "
            "pytest -m contract --update-openapi-snapshot"
        )

    expected = _strip_pydantic_schemas(json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8")))

    assert _normalized_json(current) == _normalized_json(expected)
