
"""add_hot_score_to_articles

Revision ID: 14a34926fe1e
Revises: e021dbf2e9df
Create Date: 2025-12-19 00:57:50.377830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a34926fe1e'
down_revision = 'e021dbf2e9df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('hot_score', sa.Integer(), nullable=True))
    op.drop_constraint('articles_source_url_unique', 'articles', type_='unique')
    op.create_index(op.f('ix_articles_hot_score'), 'articles', ['hot_score'], unique=False)
    op.create_index(op.f('ix_articles_source_url'), 'articles', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_source_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_hot_score'), table_name='articles')
    op.create_unique_constraint('articles_source_url_unique', 'articles', ['source_url'])
    op.drop_column('articles', 'hot_score')
    # ### end Alembic commands ###
