"""add_read_time_minutes_to_articles

Revision ID: 563b452aad27
Revises: 9815e4acd2e9
Create Date: 2025-12-19 01:21:53.500166

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "563b452aad27"
down_revision = "9815e4acd2e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("read_time_minutes", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "read_time_minutes")
    # ### end Alembic commands ###
