
"""add_published_date_to_articles

Revision ID: 9815e4acd2e9
Revises: c539d69b3ccb
Create Date: 2025-12-19 01:14:17.175133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9815e4acd2e9'
down_revision = 'c539d69b3ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_articles_published_date'), 'articles', ['published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_published_date'), table_name='articles')
    op.drop_column('articles', 'published_date')
    # ### end Alembic commands ###
