
"""add_hot_score_to_videos

Revision ID: c539d69b3ccb
Revises: 14a34926fe1e
Create Date: 2025-12-19 01:08:55.192793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c539d69b3ccb'
down_revision = '14a34926fe1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hot_score', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('published_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_videos_hot_score'), 'videos', ['hot_score'], unique=False)
    op.create_index(op.f('ix_videos_published_date'), 'videos', ['published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_published_date'), table_name='videos')
    op.drop_index(op.f('ix_videos_hot_score'), table_name='videos')
    op.drop_column('videos', 'published_date')
    op.drop_column('videos', 'hot_score')
    # ### end Alembic commands ###
