
"""add_hot_score_to_videos

Revision ID: c539d69b3ccb
Revises: 14a34926fe1e
Create Date: 2025-12-19 01:08:55.192793

MIGRATION POLICY: ADDITIVE ONLY
- Creates videos table if it doesn't exist
- Adds hot_score and published_date columns
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'c539d69b3ccb'
down_revision = '14a34926fe1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if videos table exists, create if not
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'videos' not in inspector.get_table_names():
        # Create videos table
        op.create_table('videos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(), nullable=True),
            sa.Column('summary', sa.Text(), nullable=True),
            sa.Column('video_url', sa.String(), nullable=True),
            sa.Column('source_url', sa.String(), nullable=True),
            sa.Column('thumbnail_url', sa.String(), nullable=True),
            sa.Column('source', sa.String(), nullable=True),
            sa.Column('category', sa.String(), nullable=True),
            sa.Column('duration_seconds', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
        op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
        op.create_index(op.f('ix_videos_video_url'), 'videos', ['video_url'], unique=True)
    
    # Check if hot_score column exists before adding
    columns = [col['name'] for col in inspector.get_columns('videos')]
    
    if 'hot_score' not in columns:
        op.add_column('videos', sa.Column('hot_score', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_videos_hot_score'), 'videos', ['hot_score'], unique=False)
    
    if 'published_date' not in columns:
        op.add_column('videos', sa.Column('published_date', sa.Date(), nullable=True))
        op.create_index(op.f('ix_videos_published_date'), 'videos', ['published_date'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_published_date'), table_name='videos')
    op.drop_index(op.f('ix_videos_hot_score'), table_name='videos')
    op.drop_column('videos', 'published_date')
    op.drop_column('videos', 'hot_score')
    # ### end Alembic commands ###
