
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjcjjyhitbvyyklknmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "REMOVED_PUBLISHABLE_TOKEN";

// API base URL for the Python backend
export const API_BASE_URL = "http://localhost:8000/api/v1";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to fetch from the Python backend
export async function fetchFromBackend(endpoint: string, options = {}) {
  const url = `${API_BASE_URL}${endpoint}`;
  const response = await fetch(url, {
    headers: {
      'Content-Type': 'application/json',
    },
    ...options,
  });
  
  if (!response.ok) {
    throw new Error(`API error: ${response.status}`);
  }
  
  return response.json();
}
