// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjcjjyhitbvyyklknmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0amNqanloaXRidnl5a2xrbm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODA1MjcsImV4cCI6MjA1OTc1NjUyN30.AkG1Z3vXeWou_-9RjqA5taz_xNW_lWFhjPh6mx75YF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);